### PR TITLE
Problem 1 Solution

### PR DESCRIPTION
**Pull request by caesar-cipher**

### CODE REVIEW

**Comment by ghost** [comment]
Fruits=["apple","mango","orange","banana","grapes"]
Fruits.append("kiwi")
Fruits.remove("orange")
Print(fruits)

**Comment by ghost** [comment]
​/* 
 ​    Problem 3 
  
 ​    Expected Output : 
 ​            [hello, 
 ​             , world] 
 ​*/ 
  
 ​public​ ​class​ ​Problem4​ { 
  
 ​    ​public​ ​void​ ​main​(​String​[] ​args​) { 
  
 ​        ​List<string>​ list ​=​ ​new​ ​List<string>​(); 
 ​        Problem4.​append(​"​hello​"​); 
 ​        Problem4.​append(​"​/n​"​); 
 ​        Problem4.append(​"​world​"​); 
  
 ​        ​System​.​out​.​printf(list​.​toString()); 
  
 ​    } 
 ​}

**Comment by ghost** [comment]
#include<stdio.h>
#include<iostream.h>

void main()
{
int i;char i;
printf("The first 10 natural numbers are:\n");
for (i=1;i<=10;i++)
{
printf("%d ",i);
}
printf("\n");

printf("\n\nCapital Letters:\n");   

//print captial letters alphabets

for(i = 'A'; i <='Z'; i++){

    printf("%c", i);

}

return(0);
}

**Comment by ghost** [comment]
#include<iostream.h>
#include<conio.h>
Char a;b;c;
{
a="He"
b="llo"
c="World"
Cout<<"He + llo + World"<<a+b+c;
getch();
}

**Comment by AnotherZane** [comment]
@caesar-cipher Please comment your name on this pr, else it will not be considered.

**Comment by caesar-cipher** [comment]
Omkar Jadhav

**Comment by ghost** [comment]
Pavan singh

**Pull request closed without merging**
